manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # 用最新主分支，替代无效的 v0.3
      import: app/west.yml
  self:
    path: config